version: ~> 1.0
os: osx
language: objective-c
osx_image: xcode12.5
addons:
  homebrew:
    brewfile: Brewfile.travis
    update: true
install:
  - make install
script:
  - make test
jobs:
  fast_finish: true
