version: ~> 1.0
language: objective-c
osx_image: xcode12.2
addons:
  homebrew:
    brewfile: Brewfile.travis
    update: true
install:
  - make install
script:
  - make test
matrix:
  fast_finish: true
