version: ~> 1.0
language: objective-c
osx_image: xcode61
before_install:
  - brew update
install:
  - make install
  - sudo /usr/bin/csrutil disable
  - make download
script:
  - make test
matrix:
  fast_finish: true
