version: ~> 1.0
os: osx
language: objective-c
osx_image: xcode12.5
addons:
  homebrew:
    brewfile: Brewfile.ci
    update: true
install:
  - make install
script:
  - make test
jobs:
  fast_finish: true
after_failure:
  - echo "DEBUG: Contents of /var/log/install.log"
  - cat /var/log/install.log
